project:
  type: book
  output-dir: docs

toc: true
number-sections: true
top-level-division: part
toc-depth: 3
number-depth: 4
bibliography: book.bib
csl: "ims.csl"

crossref:
  labels: arabic        # (default is arabic)
  subref-labels: roman i # (default is alpha a)


execute:
  freeze: auto

knitr:
  opts_chunk:
    comment: "#>"
    collapse: true

jupyter: ds24

format:
  html:
    theme: lumen
    code-block-bg: true
    code-block-border-left: true #"#31BAE9"
    # code-line-numbers: true
    highlight-style: atom-one
    page-layout: article

book:
  title: "Miscs for Data Science"
  author: "Xinli Xiao"
  date: last-modified
  chapters: 
    - index.qmd
    - part: "Part I: Python"
      chapters: 
        - contents/pyconcepts/setup.qmd
        - contents/pyconcepts/path.qmd
        - contents/pyconcepts/virtenv.qmd
        - contents/pyconcepts/concepts.qmd
    - part: "Part II: R"
      chapters:
        - contents/rconcepts/r.qmd
    - part: "Part III: Tools"
      chapters:
        - contents/tools/re.qmd
    # - contents/references.qmd
  sidebar:
    style: floating
    pinned: true
    align: center
    border: true
    search: true
    collapse-level: 1
    alignment: "center"
  page-navigation: true


    



